name: Release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

env:
  GH_TOKEN: ${{ github.token }}

jobs:
  gh-release-draft:
    runs-on: ubuntu-latest
    steps:
      - name: Create a GitHub release
        run: |
          # Check if release exists; if not, create it
          if ! gh release -R ${{ github.repository }} view ${{ github.ref_name }} --json id > /dev/null 2>&1; then
            gh release -R ${{ github.repository }} create ${{ github.ref_name }} --draft --generate-notes
          else
            echo "Release ${{ github.ref_name }} already exists, skipping."
          fi

  setup:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.variables.outputs.version }}

    steps:
      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v5

      - name: Set output variables
        id: variables
        run: |
          VERSION="${GITHUB_REF_NAME}"
          if [[ $VERSION =~ ^v[0-9].* ]]; then
            VERSION=${VERSION#"v"}
          fi
          echo "VERSION: ${VERSION}"
          echo "version=${VERSION}" >> $GITHUB_OUTPUT

  linux-musl:
    needs:
      - setup
      - gh-release-draft
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, ubuntu-24.04-arm]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v7
      - run: docker run --rm -v $PWD:/mnt -w /mnt crystallang/crystal:latest-alpine shards build ameba -Dpreview_mt --release --static
      - run: tar zcf ameba-${{ needs.setup.outputs.version }}-linux-musl-$(uname -m).tar.gz -C bin ameba
      - run: gh release -R ${{ github.repository }} upload ${{ github.ref_name }} ameba-${{ needs.setup.outputs.version }}-linux-musl-$(uname -m).tar.gz

  darwin:
    needs:
      - setup
      - gh-release-draft
    strategy:
      fail-fast: false
      matrix:
        include:
          - { os: macos-15, arch: aarch64 }
          - { os: macos-15-intel, arch: x86_64 }
    runs-on: ${{ matrix.os }}
    steps:
      - uses: crystal-lang/install-crystal@v1
      - uses: actions/checkout@v7
      - run: shards build ameba -Dpreview_mt --release
      - run: tar zcf ameba-${{ needs.setup.outputs.version }}-darwin-${{ matrix.arch }}.tar.gz -C bin ameba ameba.dwarf
      - run: gh release -R ${{ github.repository }} upload ${{ github.ref_name }} ameba-${{ needs.setup.outputs.version }}-darwin-${{ matrix.arch }}.tar.gz

  x86_64-windows-msvc:
    needs:
      - setup
      - gh-release-draft
    runs-on: windows-2025
    steps:
      - uses: crystal-lang/install-crystal@v1
      - uses: actions/checkout@v7
      - run: shards build ameba -Dpreview_mt --release --static
      - run: cd bin; 7z a -tzip ../ameba-${{ needs.setup.outputs.version }}-windows-msvc-x86_64.zip ameba.exe ameba.pdb
      - run: gh release -R ${{ github.repository }} upload ${{ github.ref_name }} ameba-${{ needs.setup.outputs.version }}-windows-msvc-x86_64.zip
